### PR TITLE
mcrypt => openssl

### PR DESCRIPTION
**Pull request by hranicka**
Hi.

Since the GoPay API 2.5 uses mcrypt which has been [deprecated as of PHP 7.1](http://php.net/manual/en/migration71.deprecated.php) and will be removed.

I've removed the hard-coded dependency on mcrypt extension.

I've added `openssl` implementation with the same behavior. See tests.

`openssl` is now default when possible. If not available, deprecated `mcrypt` is used.

### CODE REVIEW

**Comment by f3l1x** [comment]
Look's great. I was wondering about some changes, but I guess it could be merged and I will update it by my self.

- final modificator for implementation of Crypt
- phpDoc for Crypt inferface
- usage of already created crypt in `GopayHelper::crypt`, it creates actually new instance every time, right?

**Comment by hranicka** [comment]
@f3l1x so ok, here you are :)

**Comment by f3l1x** [comment]
In fact, this is not BC, right @hranicka? 

It can be tagged as 2.5.2? O do you think 2.6.0?

**Comment by hranicka** [comment]
I'd prefer v2.5.2 too, since there is no BC-break. As you said :)

**Comment by hranicka** [comment]
Thanks @f3l1x .

Just a technical question: What is the purpose of commit squashing like [here](https://github.com/Markette/GopayApi/commit/75b3f268897c565ceb0f595cf60a54076e5b0521)? :) It should be a single commit. There are also `.travis.yml` changes, `composer.json` changes, refactoring, implementation, refactoring again, ... :)

But agree, I should have to tidy up selfs in this PR :(

**Pull request merged**
