### PR TITLE
QA - codesniffer, editorconfig, etc

### PR DESCRIPTION
**Pull request by f3l1x**

### CODE REVIEW

**Comment by f3l1x** [comment]
I was wondering about release 2.5.2 and prepare next minor version 2.6.0. There could we drop drop php 5.3,5.4,5.5. What do you think?

**Comment by hranicka** [comment]
Drop of PHP <5.6 is a BC-break, shouldn't it be released as version 3? Yes, nobody should use PHP <5.6 in 2017, but someone should have a legacy crap and is forced to use older PHP versions. If someone rely on semantic versioning then will have to update dependencies.

What about release v3 and drop all older versions than PHP 7.0?

**Comment by f3l1x** [comment]
Mmm. I like and idea of version 3.0 and drop all older then 7.0. :+1: Thanks for an advice.

**Comment by f3l1x** [comment]
We should also figure out what to do with PHP 7.1 and mcrypt deprecation.

https://travis-ci.org/Markette/GopayApi/builds/185738010

@hranicka

**Comment by hranicka** [comment]
Exclude it from a static analysis tool? I think I've solved it only in Unit Tests.

**Comment by f3l1x** [comment]
Well, let say we could `mute` with a `@`. But be prepare for next pull request in 2018, `mcrypt` will be removed in 7.2. 

:-)

**Comment by hranicka** [comment]
When it will be removed, a common behavior of this API suite will be unchanged (comparing PHP 7.0, 7.1, 7.2) or not? Only `MCrypt` class will be exist here but won't be really used in PHP 7.0+, right?

**Comment by hranicka** [comment]
I think it should not be muted with `@`.

But the whole `MCrypt` class should be removed from a static analysis tool. Is it possible? :)

**Pull request merged**
